### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by adminlove520** [littleclaw/AutoDing#1]
请问有好几个时段的打卡  怎么设置呀  就是上班、下班  一共4个时段

**Comment by littleclaw** [comment]
定时打卡只能设置上班和下班两个时段的。其实这个APP主要功能不在定时打卡，开发出来主要是为了用远程推送打卡的，想啥时候打卡用手机给打卡机发打卡指令就好，打卡成功会给你设置的邮箱发邮件通知，不比定时打卡香多了？
