### ISSUE TITLE
请问有使用教程吗，不知道咋用

### ISSUE THREAD

**Issue by daisy-disc** [littleclaw/AutoDing#2]

**Comment by littleclaw** [comment]
目前没有详尽的教程，因为中间一些设置因手机品牌而各异，基本的使用方式就是：

1. 准备两台安卓手机，一个是你日常使用的，一个是长期放在单位用来专门打卡的，后面我会叫它打卡机。两台手机上都装上这个app
2. 打开**打卡机**上装的这个app，在设置里面点邮箱设置，把最下面的收件QQ邮箱填写成自己的邮箱，输完点下测试，能收到测试邮件了点保存邮箱设置
3. 打开**打卡机**上装的这个app，把这上面设置下面的注册id复制，再打开你手机上这个app，在设置里点发送推送，在最上面输入框里粘贴上刚才复制的注册ID，复制完点第一个推送检查指令，如果能收到邮件通知说明成功了，成功后这个注册ID会自动保存下来
4. 正式打卡的时候就是在自己手机上打开app，点设置——发送推送————推送打开钉钉指令，然后等待打卡机收到指令后打开打卡机上已经登录好的钉钉，然后钉钉极速打卡成功，app检测到有打卡成功的通知后会发邮箱通知你。

上面是基本使用方法，具体用的时候要设置好钉钉极速打卡、把锁屏关掉或者应用设置显示在锁屏上，总之要把一系列会影响打卡机app运行、唤醒手机的设置好，这些根据手机品牌不同设置方法不尽相同，这些可以参考readme

**Comment by daisy-disc** [comment]
> 目前没有详尽的教程，因为中间一些设置因手机品牌而各异，基本的使用方式就是：
> 
> 1. 准备两台安卓手机，一个是你日常使用的，一个是长期放在单位用来专门打卡的，后面我会叫它打卡机。两台手机上都装上这个app
> 2. 打开**打卡机**上装的这个app，在设置里面点邮箱设置，把最下面的收件QQ邮箱填写成自己的邮箱，输完点下测试，能收到测试邮件了点保存邮箱设置
> 3. 打开**打卡机**上装的这个app，把这上面设置下面的注册id复制，再打开你手机上这个app，在设置里点发送推送，在最上面输入框里粘贴上刚才复制的注册ID，复制完点第一个推送检查指令，如果能收到邮件通知说明成功了，成功后这个注册ID会自动保存下来
> 4. 正式打卡的时候就是在自己手机上打开app，点设置——发送推送————推送打开钉钉指令，然后等待打卡机收到指令后打开打卡机上已经登录好的钉钉，然后钉钉极速打卡成功，app检测到有打卡成功的通知后会发邮箱通知你。
> 
> 上面是基本使用方法，具体用的时候要设置好钉钉极速打卡、把锁屏关掉或者应用设置显示在锁屏上，总之要把一系列会影响打卡机app运行、唤醒手机的设置好，这些根据手机品牌不同设置方法不尽相同，这些可以参考readme

感谢你的回复，我的意思是如何生成APK，我好像没找到安装包

**Comment by daisy-disc** [comment]
> > 目前没有详尽的教程，因为中间一些设置因手机品牌而各异，基本的使用方式就是：
> > 
> > 1. 准备两台安卓手机，一个是你日常使用的，一个是长期放在单位用来专门打卡的，后面我会叫它打卡机。两台手机上都装上这个app
> > 2. 打开**打卡机**上装的这个app，在设置里面点邮箱设置，把最下面的收件QQ邮箱填写成自己的邮箱，输完点下测试，能收到测试邮件了点保存邮箱设置
> > 3. 打开**打卡机**上装的这个app，把这上面设置下面的注册id复制，再打开你手机上这个app，在设置里点发送推送，在最上面输入框里粘贴上刚才复制的注册ID，复制完点第一个推送检查指令，如果能收到邮件通知说明成功了，成功后这个注册ID会自动保存下来
> > 4. 正式打卡的时候就是在自己手机上打开app，点设置——发送推送————推送打开钉钉指令，然后等待打卡机收到指令后打开打卡机上已经登录好的钉钉，然后钉钉极速打卡成功，app检测到有打卡成功的通知后会发邮箱通知你。
> > 
> > 上面是基本使用方法，具体用的时候要设置好钉钉极速打卡、把锁屏关掉或者应用设置显示在锁屏上，总之要把一系列会影响打卡机app运行、唤醒手机的设置好，这些根据手机品牌不同设置方法不尽相同，这些可以参考readme
> 
> 感谢你的回复，我的意思是如何生成APK，我好像没找到安装包

找到了找到了，多谢啦
