### ISSUE TITLE
打卡时间秒数

### ISSUE THREAD

**Issue by soulmate-xz** [littleclaw/AutoDing#3]
可以添加打卡时间秒数设置的功能吗, 总是在0秒打卡感觉还是有点不正常

**Comment by littleclaw** [comment]
定时打卡是移植别的项目而来的，我的项目主要侧重于实现远程指令打卡，所以我大概率不会再改动定时打卡部分的功能了，你可以参考别人的项目，看看可能已经迭代出了你需要的功能了。
[项目](https://github.com/AndroidCoderPeng/AutoDingding)

**Comment by littleclaw** [comment]
鉴于此功能不在我项目侧重点，定时打卡相关功能将长期不变
