### ISSUE TITLE
手动打卡总是失败

### ISSUE THREAD

**Issue by Masterpan4** [littleclaw/AutoDing#4]
有时候钉钉极速打开卡不会响应，但是远程打卡那个，每次都顺利进入到了打卡页面，但是老是打卡不成功
       邮件里是这么说的:"查找上班打卡或下班打卡大按钮失败，点击打卡失败，准备查看页面结果，页面结果判断打卡失败,准备回退"
        想问一下老哥这个问题怎么解决呀，我远程推送的时候也有看到进入到钉钉的打卡界面，但就是模拟点击这块不成功

**Comment by littleclaw** [comment]
今天刚看到，检查了一下，发现是打卡页面钉钉重构成非原生页面了，中间一大块内容无法通过之前找“上班打卡”“下班打卡”的方式找到组件，后面考虑按页面百分比的方式点一下屏幕中间偏下位置，不过这种方式兼容性肯定不太好，希望你有心理准备

**Comment by littleclaw** [comment]
新版本现已发布[版本1.1.4](https://github.com/littleclaw/AutoDing/releases/tag/1.1.4)，这版变更了手动打卡的执行逻辑，目前在我手机上测试了能跑，兼容问题还需要各位使用者测试发现。 

目前就先关闭此issue，如果仍有问题请开新issue.
