### ISSUE TITLE
较新版本安卓系统无法使用

### ISSUE THREAD

**Issue by alex3236** [littleclaw/AutoDing#5]
新一点的安卓系统似乎给不了存储权限导致无法使用，提示授权失败

**Comment by littleclaw** [comment]
emm，请详细给出出现问题的操作路径，以及用的是什么牌子的手机，安卓版本是多少。存储权限应用设置里也可以授权的吧，如果应用没有成功引导弹窗授权，可以尝试在设置里应用权限管理里给加上授权试试。

**Comment by littleclaw** [comment]
已经把旧版授权代码去掉了，现在新版应该可以正常正常使用了
