### ISSUE TITLE
隔壁AutoDingding 更新了新的应用包来规避， 这个是更新了签名吗

### ISSUE THREAD

**Issue by 1394805163** [littleclaw/AutoDing#6]
因为我禁止了应用列表以后老是给我弹出申请权限弄得一会好一会不好的我是一台vivo的老手机

**Comment by littleclaw** [comment]
目前还没有更新包名，理论上更新包名应该可以解决问题，我下次抽个时间换个包名再发一版

**Comment by littleclaw** [comment]
已经更新了包名，并给出了自行修改包名的要点
