### ISSUE TITLE
尝试了自己打包，使用gradle build，报错了

### ISSUE THREAD

**Issue by kiter-zero** [littleclaw/AutoDing#7]
![image](https://github.com/user-attachments/assets/4e38211c-2f78-4e31-8aa7-5dd12c0fa937)

**Comment by kiter-zero** [comment]
![image](https://github.com/user-attachments/assets/d08ab5e3-da9f-4b50-852d-b22e6b3661d6)
另外，修改applicationId后，好像好多地方出现这个包名的，都要修改

**Comment by kiter-zero** [comment]
有没有伙伴自己打包成功的，求教下

**Comment by littleclaw** [comment]
manifest里面有包名的三处都要改，之前包名是com.pengxh.autodingding，现在已经改成了com.furry.rimet，报错的截图没有看到具体的信息，你应该带上--info 或者--debug这样报错里面的信息才更全面一些。

**Comment by littleclaw** [comment]
> 有没有伙伴自己打包成功的，求教下

简单点的办法，你全局搜索包名com.furry.rimet, 把出现的都换了，再去换推送的appKey appSecret

**Comment by kiter-zero** [comment]
好的，谢谢楼主，我试试

**Comment by littleclaw** [comment]
因长时间无后续反馈，所以关闭
